apiVersion: v1                  # Версия API для Service. v1 - самый базовый API.
kind: Service                   # Тип объекта: Service.
metadata:
  name: testappservice  # Уникальное имя сервиса в рамках неймспейса.
spec:
  type: NodePort                # Тип сервиса: NodePort — позволяет обращаться к приложению через порт на любом узле кластера.
  selector:                     # Селектор, по которому сервис будет находить нужные поды.
    app: testapp         # Важно, чтобы этот label совпадал с label подов (или Deployment) для успешного роутинга.
  ports:
    - protocol: TCP             # Протокол, который мы используем (TCP, UDP и т.д.).
      port: 8080                # "Внутренний" порт сервиса. Трафик приходит на этот порт внутри кластера.
      targetPort: 8080          # Порт внутри контейнера, на который надо перенаправлять трафик.
